name: CoolPlugin
version: ${project.version}
main: cool.coolplugin.CoolPlugin
api-version: 1.19
authors: [ rai/wooof ]
description: Adds various things for vanilla MC servers!

commands:
  color:
    description: "changes your name color!"
    usage: /<command>
    aliases: [changecolor, setcolor]
  stats:
    description: "view things like a player's UUID!"
    usage: /<command>
    aliases: [viewstats, whois, checkplayer]
  server:
    description: "view the server's stats"
    usage: /<command>
    aliases: [serverstats]
  unload:
    description: "unload the plugin (Console Only)"
    usage: /<command>
  nick:
    description: "changes your chat name"
    usage: /<command>
    aliases: [nickname, changename]
  restrict:
    description: "restricts player from using nicknames"
    usage: /<command>
    aliases: [nonick, nickrestrict]